name: hoy_focus
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  lottie: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.3
  confetti: ^0.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_splash.png
    - assets/lottie/key_animation.json
    - assets/lottie/walking_animation.json
    - assets/lottie/walk_animation.json
    - assets/lottie/ghost2_animation.json
    - assets/lottie/break_animation.json
    - assets/lottie/home_animation.json
